env:
  global:
    - CC_TEST_REPORTER_ID=a4181d45480e49e1776b262dba894df97b6592e0fde285fd78dd0aa16bfc87ca
language: node_js
node_js:
  - "stable"

before_script:
 - psql -c 'create database stackoverflow_lite_test;' -U postgres
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script: npm run test && npm run react:test

cache:
  directories:
    - "node_modules"
after_success: 
 - npm run coveralls
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
